# Введение в матрицы Python и NumPy #

Добро пожаловать в ваш первый блокнот этой специализации! В этом блокноте вы будете использовать NumPy для создания двумерных массивов и простого выполнения математических операций. NumPy (Numerical Python) — это открытый пакет, широко используемый в науке и технике. Не стесняйтесь пропустить этот блокнот, если вы уже свободно владеете NumPy.

**После этого задания вы сможете:**
- Использовать Jupyter Notebook и его функции.
- Использовать функции NumPy для создания массивов и операции с массивами NumPy.
- Использовать индексацию и срезы для двумерных массивов.
- Находить форму массива, изменять её и складывать массивы горизонтально и вертикально.

**Инструкции**
- Вы будете использовать Python 3.
- Перемещайтесь по ячейкам с помощью `Shift`+`Enter`. Альтернативно, вы можете нажать `Run` в меню.

## Содержание ##
[О блокнотах Jupyter](#0)
- [1 - Основы NumPy](#1)
    - [1.1 - Пакеты](#1-1)
    - [1.2 - Преимущества использования массивов NumPy](#1-2)
    - [1.3 - Как создавать массивы NumPy](#1-3)
    - [1.4 - Подробнее о массивах NumPy](#1-4)
- [2 - Многомерные массивы](#2)
    - [2.1 - Нахождение размера, формы и размерности](#2-1)
- [3 - Математические операции с массивами](#3)
    - [3.1 - Умножение вектора на скаляр (broadcasting)](#3-1)
- [4 - Индексация и срезы](#4)
    - [4.1 - Индексация](#4-1)
    - [4.2 - Срезы](#4-2)
- [5 - Сложение](#5)
- [6 - Упражнения](#6)

<a name='0'></a>
## О блокнотах Jupyter ##


Блокноты Jupyter — это интерактивные журналы кодирования, которые объединяют живой код, пояснительный текст, уравнения, визуализации и другие мультимедийные ресурсы в одном документе. В качестве первого упражнения запустите тестовый фрагмент ниже и ячейку с оператором print для "Hello World".

In [1]:
# Запустите "Hello World" в ячейке ниже, чтобы напечатать "Hello World".
test = "Hello World"

In [2]:
print(test)

Hello World


<a name='1'></a>
# 1 - Основы NumPy #

NumPy — это основной пакет для научных вычислений в Python. Он выполняет широкий спектр сложных математических операций с высокой эффективностью. В этой практической лаборатории вы изучите несколько ключевых функций NumPy, которые помогут вам в будущих заданиях, таких как создание массивов, срезы, индексация, изменение формы и сложение.

<a name='1-1'></a>
## 1.1 - Пакеты ##

Прежде чем начать, вы должны импортировать NumPy, чтобы загрузить его функции. Как вы можете заметить, даже если ожидаемого вывода нет, когда вы запускаете эту ячейку, Jupyter Notebook импортирует пакет (часто называемый библиотекой) и его функции. Попробуйте сами и запустите следующую ячейку.

In [3]:
import numpy as np

<a name='1-2'></a>
## 1.2 - Преимущества использования массивов NumPy ##

Массивы являются одной из основных структур данных библиотеки NumPy, необходимых для организации ваших данных. Вы можете думать о них как о сетке значений, все одного типа. Если вы раньше использовали списки Python, вы можете помнить, что они удобны, так как вы можете хранить разные типы данных. Однако списки Python ограничены в функциях и занимают больше места и времени для обработки, чем массивы NumPy.

NumPy предоставляет объект массива, который намного быстрее и компактнее, чем списки Python. Благодаря обширной интеграции API, библиотека предлагает множество встроенных функций, которые значительно упрощают вычисления всего несколькими строками кода. Это может быть огромным преимуществом при выполнении математических операций с большими наборами данных.

Объект массива в NumPy называется `ndarray`, что означает 'n-мерный массив'. Для начала вы будете использовать один из самых распространенных типов массивов: одномерный массив ('1-D'). Одномерный массив представляет собой стандартный список значений entirely в одном измерении. Помните, что в NumPy все элементы массива имеют одинаковый тип.

In [4]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


<a name='1-3'></a>
## 1.3 - Как создавать массивы NumPy ##

Есть несколько способов создать массив в NumPy. Вы можете создать одномерный массив, просто используя функцию `array()`, которая принимает список значений в качестве аргумента и возвращает одномерный массив.

In [5]:
# Создайте и напечатайте массив NumPy 'a', содержащий элементы 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Другой способ реализовать массив — использовать `np.arange()`. Эта функция возвращает массив равномерно распределенных значений в заданном интервале. Чтобы узнать больше об аргументах, которые принимает эта функция, в Jupyter Notebook есть мощная функция, которая позволяет вам получить доступ к документации любой функции, просто нажав `shift+tab` на клавиатуре при нажатии на функцию. Попробуйте это для встроенной документации `np.arange()`.

In [6]:
# Создайте массив с 3 целыми числами, начиная с целого числа по умолчанию 0.
b = np.arange(3)
print(b)

[0 1 2]


In [7]:
# Создайте массив, который начинается с целого числа 1, заканчивается на 20, с шагом 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


Что если вы хотите создать массив с пятью равномерно распределенными значениями в интервале от 0 до 100? Как вы можете заметить, у вас есть 3 параметра, которые должна принимать функция. Один параметр — начальное число, в данном случае 0, конечное число 100 и количество элементов в массиве, в данном случае 5. NumPy имеет функцию, которая позволяет вам сделать именно это, используя `np.linspace()`.

In [8]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


Вы заметили, что вывод функции представлен в форме значений с плавающей точкой (например, "... 25. 50. ...")? Причина в том, что тип по умолчанию для значений в функции NumPy `np.linspace` — это плавающая точка (`np.float64`). Вы можете легко указать тип данных с помощью `dtype`. Если вы обратитесь к встроенной документации функций, вы можете заметить, что большинство функций принимают необязательный параметр `dtype`. В дополнение к float, NumPy имеет несколько других типов данных, таких как `int` и `char`.

Чтобы изменить тип на целые числа, вам нужно установить dtype в `int`. Вы можете сделать это даже в предыдущих функциях. Не стесняйтесь попробовать и изменить ячейки для вывода желаемого типа данных.

In [9]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [10]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [11]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [12]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Печатает тип данных массива

['Welcome to Math for ML!']
<U23


Вы заметили, что вывод типа данных массива `char_arr` — `<U23`?
Это означает, что строка (`'Welcome to Math for ML!'`) является 23-символьной (23) unicode строкой (`U`) на архитектуре с little-endian (`<`). Вы можете узнать больше о типах данных [здесь](https://docs.scipy.org/doc/NumPy-1.13.0/reference/arrays.dtypes.html).

<a name='1-4'></a>
## 1.4 - Подробнее о массивах NumPy ##

Одно из преимуществ использования NumPy заключается в том, что вы можете легко создавать массивы с помощью встроенных функций, таких как:
- `np.ones()` - Возвращает новый массив, устанавливая значения в единицы.
- `np.zeros()` - Возвращает новый массив, устанавливая значения в нули.
- `np.empty()` - Возвращает новый неинициализированный массив.
- `np.random.rand()` - Возвращает новый массив со случайными значениями.

In [13]:
# Возвращает новый массив формы 3, заполненный единицами.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [14]:
# Возвращает новый массив формы 3, заполненный нулями.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [15]:
# Возвращает новый массив формы 3, без инициализации записей.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [16]:
# Возвращает новый массив формы 3 со случайными числами между 0 и 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.52649438 0.77712451 0.73316068]


<a name='2'></a>
# 2 - Многомерные массивы #
С NumPy вы также можете создавать массивы более чем с одним измерением. В приведенных выше примерах вы имели дело с одномерными массивами, где вы можете получить доступ к их элементам, используя один индекс. Многомерный массив имеет более одного столбца. Думайте о многомерном массиве как о листе Excel, где каждая строка/столбец представляет измерение.

In [17]:
# Создайте двумерный массив (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


Альтернативный способ создания многомерного массива — это изменение формы исходного одномерного массива. Используя `np.reshape()`, вы можете переставить элементы предыдущего массива в новую форму.

In [18]:
# 1-D массив
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Многомерный массив с использованием reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # массив для изменения формы
               (2,3) # размерности нового массива
              )
# Напечатайте новый 2-D массив с двумя строками и тремя столбцами
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


<!-- упражнение: можете ли вы создать массив с тремя строками и 4 столбцами, используя np.ones. Какова размерность, размер и -->